# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
## https://github.com/edzer/sfr/issues/142

language: R
sudo: required

cache: packages

# https://github.com/ropensci/rgbif/blob/master/.travis.yml#L9
dist: trusty

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libcgal-dev
  - sudo apt-get install libcgal-demo
  - sudo apt-get install cmake g++


r_github_packages:
  - jimhester/covr

after_success:
  - R -e 'covr::codecov()'
